# 1. Load Car93 Data set

In [2]:
import pandas as pd

In [9]:
cars=pd.read_csv(r"E:\Adv Analytics\Datasets\Cars93.csv")
cars

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8        25   
1         Acura   Legend  Midsize       29.2   33.9       38.7        18   
2          Audi       90  Compact       25.9   29.1       32.3        20   
3          Audi      100  Midsize       30.8   37.7       44.6        19   
4           BMW     535i  Midsize       23.7   30.0       36.2        22   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7        17   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4        21   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7        18   
91        Volvo      240  Compact       21.8   22.7       23.5        21   
92        Volvo      850  Midsize       24.8   26.7       28.5        20   

    MPG.highway             AirBags DriveTrain  ... Fuel.tank.capacity  \
0            31                None      Front  ...               13.2   
1            25  Driver & Passenger      Front  ...               18.0   
2            26         Driver only      Front  ...               16.9   
3            26  Driver & Passenger      Front  ...               21.1   
4            30         Driver only       Rear  ...               21.1   
..          ...                 ...        ...  ...                ...   
88           21                None      Front  ...               21.1   
89           30                None      Front  ...               18.5   
90           25                None      Front  ...               18.5   
91           28         Driver only       Rear  ...               15.8   
92           28  Driver & Passenger      Front  ...               19.3   

    Passengers  Length  Wheelbase  Width Turn.circle  Rear.seat.room  \
0            5     177        102     68          37            26.5   
1            5     195        115     71          38            30.0   
2            5     180        102     67          37            28.0   
3            6     193        106     70          37            31.0   
4            4     186        109     69          39            27.0   
..         ...     ...        ...    ...         ...             ...   
88           7     187        115     72          38            34.0   
89           5     180        103     67          35            31.5   
90           4     159         97     66          36            26.0   
91           5     190        104     67          37            29.5   
92           5     184        105     69          38            30.0   

    Luggage.room  Weight   Origin  
0           11.0    2705  non-USA  
1           15.0    3560  non-USA  
2           14.0    3375  non-USA  
3           17.0    3405  non-USA  
4           13.0    3640  non-USA  
..           ...     ...      ...  
88           NaN    3960  non-USA  
89          14.0    2985  non-USA  
90          15.0    2810  non-USA  
91          14.0    2985  non-USA  
92          15.0    3245  non-USA  

[93 rows x 26 columns]

# 2 using crosstab for AirBags and Type atrribute


In [10]:
crosstab_col = pd.crosstab(index=cars['AirBags'],columns=cars["Type"])
crosstab_col

Type                Compact  Large  Midsize  Small  Sporty  Van
AirBags                                                        
Driver & Passenger        2      4        7      0       3    0
Driver only               9      7       11      5       8    3
None                      5      0        4     16       3    6

# 3. calculate marginal probability for Driver & Passenger,Driver only,None

In [1]:
import numpy as np
from  scipy.stats.contingency import margins

In [14]:
x,y=margins(crosstab_col)
x

array([[16],
       [43],
       [34]], dtype=int64)

In [15]:
y

array([[16, 11, 22, 21, 14,  9]], dtype=int64)

In [16]:
mar_prb =[]
for i in x:
    prb = i/sum(x)
    mar_prb.append(prb)
mar_prb


[array([0.17204301]), array([0.46236559]), array([0.3655914])]

In [17]:
sum(mar_prb)

array([1.])

# 4. calculate marginal probability for Compact , Large , Midsize , Small , Sporty , Van

In [26]:
y=y.T
mar_prb =[]
for i in y:
    prb = i/sum(x)
    mar_prb.append(prb)
mar_prb


[array([0.17204301]),
 array([0.11827957]),
 array([0.23655914]),
 array([0.22580645]),
 array([0.15053763]),
 array([0.09677419])]

In [27]:
sum(mar_prb)

array([1.])

# 5. Load min_telcom Data Set 

In [28]:
telecom=pd.read_csv(r"E:\Adv Analytics\Datasets\Telecom.csv")
telecom

Gender TT_gt_100 Response
0        F         Y        N
1        M         N        N
2        M         N        N
3        F         Y        Y
4        F         N        N
..     ...       ...      ...
145      F         Y        Y
146      M         N        Y
147      M         N        N
148      M         N        N
149      F         N        N

[150 rows x 3 columns]

# 6. Calculate Marginal probability for Gender

In [29]:
crosstab2=pd.crosstab(telecom['Gender'],columns=telecom['Response'])
crosstab2

Response   N   Y
Gender          
F         13  64
M         59  14

# 7. calculate the Marginal Probability for bought and not bought

In [ ]:
x,y=margins(crosstab)
x

# 8. Load Salaries data set

# 9. create cross tab on discipline and rank

# 10. Calculate conditional probability of AssocProf for each rank

# 11. load the HR_comma_sep data set